### ISSUE TITLE
Server wouldn't start (SyntaxError)

### ISSUE THREAD

**Issue by sstruct** [fullstackreact/food-lookup-demo#29]
```
➜  food-lookup-demo git:(master) ✗ npm run server

> lookup-server@0.0.1 server /Volumes/caicloud/lab/food-lookup-demo
> node server.js

/Volumes/caicloud/lab/food-lookup-demo/server.js:62
    );
    ^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Darwin 16.6.0
npm ERR! argv "/Users/yangzi/.nvm/versions/node/v6.9.4/bin/node" "/Users/yangzi/.nvm/versions/node/v6.9.4/bin/npm" "run" "server"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! lookup-server@0.0.1 server: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lookup-server@0.0.1 server script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lookup-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lookup-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls lookup-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Volumes/caicloud/lab/food-lookup-demo/npm-debug.log
```

It seems that the server scripts has some syntax wrong, please have a look.

**Comment by acco** [comment]
@sstruct Shoot. I removed a dangling comma but forgot to push. Just did. If you pull and try again it should work.

Thanks for your patience!
