### ISSUE TITLE
Cannot find module 'sql.js'

### ISSUE THREAD

**Issue by sugandhgoyal** [fullstackreact/food-lookup-demo#37]
Whenever I run npm run server it gives me this error. I have googled it a lot but haven't found the solution. what should i do?
module.js:487
    throw err;
    ^

Error: Cannot find module 'sql.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:/Users/ATUL/Documents/GitHub/food-lookup-demo/server.js:3:16)
    at Module._compile (module.js:569:30)
    at loader (C:\Users\ATUL\Documents\GitHub\food-lookup-demo\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\ATUL\Documents\GitHub\food-lookup-demo\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lookup-server@0.0.1 server: `babel-node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lookup-server@0.0.1 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ATUL\AppData\Roaming\npm-cache\_logs\2017-08-25T18_50_06_252Z-debug.lo

**Comment by acco** [comment]
Hi @sugandhgoyal 

I just tested it from scratch and it's working for me. Did you `npm i` in both the top-level directory and inside `client/`?

Lmk

**Comment by TiE23** [comment]
Since I figure someone Googling the same exact error as me will show up here - in the Fullstack React book teaching how to write your own GraphQL server it's never said to add sql to your dependencies. So if you're having this issue trying to run sqlite3 on the seedData.js example file just run ```npm i sql@0.67.0 --save --save-exact``` and that should solve things for you.

**Comment by mazer-rakham** [comment]
This needs to be more easily accessible. I was tearing my head out for an hour trying to write sqlite functions.
